mod compositions;
mod consts;
mod decompositions;

pub use compositions::*;
pub use decompositions::*;

pub use consts::*;

const PREFIX_STR: &str = "/* This file is autogenerated using una-bakery crate. */";
const LINE_WIDTH: usize = 120;
const INDENT_LEN: usize = 4;
